begin;

alter table relife.clinics drop constraint if exists clinics_status_check;
update relife.clinics set status='archived' where status not in ('draft','setup','ready','active','suspended','archived');
alter table relife.clinics add constraint clinics_status_check check (status in ('draft','setup','ready','active','suspended','archived'));
alter table relife.clinics alter column status set default 'draft';

create table if not exists relife.clinic_settings (
 organization_id uuid not null, clinic_id uuid not null,
 clinic_type text not null default 'other' check (clinic_type in ('physiotherapy','dental','doctor_chamber','other')),
 branch_name text not null default '', address text not null default '', phone text not null default '', email text not null default '', logo_url text not null default '', currency text not null default 'BDT', locale text not null default 'en', updated_by text not null default 'system', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 primary key (organization_id,clinic_id), foreign key (organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict);
create table if not exists relife.clinic_operating_hours (
 organization_id uuid not null, clinic_id uuid not null, day_of_week smallint not null check(day_of_week between 1 and 7), is_open boolean not null default true, opens_at time, closes_at time, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 primary key(organization_id,clinic_id,day_of_week), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict,
 check((not is_open and opens_at is null and closes_at is null) or (is_open and opens_at is not null and closes_at is not null and closes_at>opens_at)));
create table if not exists relife.feature_catalog (
 feature_key text primary key, label text not null, description text not null default '', module_group text not null check(module_group in ('core','optional')), domain text not null check(domain in ('core','patients','appointments','staff','services','finance','reports','clinical','facility','chamber','inventory','messaging','engagement','files','audit')), status text not null default 'active' check(status in ('active','retired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
insert into relife.feature_catalog(feature_key,label,module_group,domain) values
 ('core.dashboard','Dashboard','core','core'),('core.patients','Patients','core','patients'),('core.appointments','Appointments','core','appointments'),('core.staff','Staff','core','staff'),('core.services','Services','core','services'),('core.finance_basic','Basic finance','core','finance'),('core.reports','Reports','core','reports'),('core.settings','Profile settings','core','core'),
 ('optional.live_chamber','Live Chamber','optional','chamber'),('optional.room_bed_runtime','Room/bed runtime','optional','facility'),('optional.clinical_notes','Clinical notes','optional','clinical'),('optional.treatment_plans','Treatment plans','optional','clinical'),('optional.packages','Packages','optional','services'),('optional.attendance','Attendance','optional','staff'),('optional.salary','Salary','optional','finance'),('optional.inventory','Inventory','optional','inventory'),('optional.sms','SMS','optional','messaging'),('optional.notifications','Notifications','optional','messaging'),('optional.files','Files/documents','optional','files'),('optional.audit_viewer','Audit viewer','optional','audit'),('optional.finance_advanced','Advanced finance','optional','finance'),('optional.machines','Machines','optional','facility'),('optional.gamification','Gamification','optional','engagement'),('optional.rewards','Rewards','optional','engagement'),('optional.live_chat','Live chat','optional','messaging')
on conflict(feature_key) do update set label=excluded.label,module_group=excluded.module_group,domain=excluded.domain,updated_at=now();
create table if not exists relife.clinic_feature_flags (
 organization_id uuid not null, clinic_id uuid not null, feature_key text not null references relife.feature_catalog(feature_key) on delete restrict, enabled boolean not null default false, enabled_by text not null default 'system', notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id,feature_key), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict);
create table if not exists relife.clinic_entitlements (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null, clinic_id uuid not null, feature_key text not null references relife.feature_catalog(feature_key) on delete restrict, status text not null default 'active' check(status in ('active','suspended','revoked')), effective_from timestamptz not null default now(), effective_until timestamptz, source text not null default 'plan' check(source in ('plan','trial','manual','migration')), plan_code text not null default '', grant_reason text not null default '', granted_by text not null default 'system', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict, check(effective_until is null or effective_until>effective_from));
create unique index if not exists clinic_entitlements_active_uidx on relife.clinic_entitlements(organization_id,clinic_id,feature_key) where status='active';
create table if not exists relife.clinic_rooms (
 organization_id uuid not null, clinic_id uuid not null, room_code text not null, display_name text not null, is_active boolean not null default true, sort_order integer not null default 0, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id,room_code), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict);
create table if not exists relife.clinic_resources (
 organization_id uuid not null, clinic_id uuid not null, resource_code text not null, display_name text not null, resource_type text not null check(resource_type in ('BED','DENTAL_CHAIR','TREATMENT_TABLE','CABIN','ROOM','MACHINE','OTHER')), room_code text, capacity integer not null default 1 check(capacity>0), gender_restriction text check(gender_restriction in ('Male','Female')), is_bookable boolean not null default false, is_runtime_only boolean not null default false, is_active boolean not null default true, sort_order integer not null default 0, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id,resource_code), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict, foreign key(organization_id,clinic_id,room_code) references relife.clinic_rooms(organization_id,clinic_id,room_code) on delete restrict);
create table if not exists relife.clinic_services (
 organization_id uuid not null, clinic_id uuid not null, service_code text not null, display_name text not null, department text not null default 'All' check(department in ('Physio','Dental','All')), price numeric(12,2) not null default 0 check(price>=0), duration_min integer not null default 30 check(duration_min>0), requires_booking boolean not null default true, requires_provider boolean not null default true, requires_resource boolean not null default false, discount_applicable boolean not null default true, tax_applicable boolean not null default false, package_eligible boolean not null default false, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id,service_code), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict);
create table if not exists relife.clinic_booking_config (
 organization_id uuid not null, clinic_id uuid not null, booking_mode text not null default 'simple' check(booking_mode in ('simple','capacity','specific_resource')), default_duration_min integer not null default 30 check(default_duration_min>0), slot_interval_min integer not null default 30 check(slot_interval_min>0), max_simultaneous integer check(max_simultaneous is null or max_simultaneous>0), provider_required boolean not null default true, resource_required boolean not null default false, block_duplicate_patient_overlap boolean not null default true, allow_walk_in boolean not null default true, cancellation_notice_min integer not null default 0 check(cancellation_notice_min>=0), late_arrival_grace_min integer not null default 0 check(late_arrival_grace_min>=0), capacity_rules jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict, check((booking_mode<>'capacity' or max_simultaneous is not null) and (booking_mode<>'specific_resource' or resource_required=true)));
create table if not exists relife.clinic_data_sources (
 organization_id uuid not null, clinic_id uuid not null, source_kind text not null check(source_kind in ('sheets_workbook','storage_bucket','storage_prefix','export_target')), source_role text not null, source_ref text not null, is_legacy boolean not null default false, status text not null default 'active' check(status in ('active','retired')), notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(organization_id,clinic_id,source_kind,source_role), foreign key(organization_id,clinic_id) references relife.clinics(organization_id,id) on delete restrict);

create index if not exists clinic_feature_flags_feature_idx on relife.clinic_feature_flags(feature_key);
create index if not exists clinic_entitlements_feature_idx on relife.clinic_entitlements(feature_key);
create index if not exists clinic_resources_room_idx on relife.clinic_resources(organization_id,clinic_id,room_code);
create index if not exists clinic_services_active_idx on relife.clinic_services(organization_id,clinic_id,department) where is_active;

grant usage on schema relife to service_role;
do $$ declare t text; tables text[]:=array['clinic_settings','clinic_operating_hours','feature_catalog','clinic_feature_flags','clinic_entitlements','clinic_rooms','clinic_resources','clinic_services','clinic_booking_config','clinic_data_sources']; begin foreach t in array tables loop execute format('alter table relife.%I enable row level security',t); execute format('revoke all on table relife.%I from anon, authenticated',t); execute format('grant select,insert,update,delete on table relife.%I to service_role',t); end loop; end $$;

create or replace function relife.clinic_feature_enabled(p_organization_id uuid,p_clinic_id uuid,p_feature_key text,p_at timestamptz default now()) returns boolean language sql stable security invoker set search_path=relife,pg_catalog as $$ select exists(select 1 from relife.clinic_feature_flags f join relife.feature_catalog c on c.feature_key=f.feature_key join relife.clinic_entitlements e on e.organization_id=f.organization_id and e.clinic_id=f.clinic_id and e.feature_key=f.feature_key where f.organization_id=p_organization_id and f.clinic_id=p_clinic_id and f.feature_key=p_feature_key and f.enabled and c.status='active' and e.status='active' and e.effective_from<=p_at and (e.effective_until is null or e.effective_until>p_at)); $$;
revoke all on function relife.clinic_feature_enabled(uuid,uuid,text,timestamptz) from public,anon,authenticated;
grant execute on function relife.clinic_feature_enabled(uuid,uuid,text,timestamptz) to service_role;

commit;
